### ISSUE TITLE
Colaboração

### ISSUE THREAD

**Issue by lucasplucena** [lucasplucena/GCMS-Lucas-Lucena#1]
Boa noite professor @ramidedantas, sua vez de participar como colaborador no [readme](https://github.com/lucasplucena/GCMS-Lucas-Lucena/blob/main/README.md).

**Comment by ramidedantas** [comment]
@lucasplucena Formate o Readme como está no meu repositório, incluindo seu nome, depois me marque aqui.

**Comment by lucasplucena** [comment]
@ramidedantas Ok professor, formatado.

**Comment by ramidedantas** [comment]
@lucasplucena Readme modificado, pode fechar issue.
